apply plugin: 'com.android.application'
// Kotlin - 插件
apply plugin: 'kotlin-android'
// Kotlin - 处理注解
apply plugin: 'kotlin-kapt'
// Kotlin - @Parcelize
apply plugin: 'kotlin-parcelize'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.qtone.camerause"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"

        multiDexEnabled true

        // UVCCamera 包含底层 C++ NDK 架构
        // UVC native 库通常没有 x86、x86_64
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a'//,'x86','x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        // 源代码兼容 Java 8 (可按需设)
        sourceCompatibility = rootProject.ext.sourceCompatibility
        // 生成的字节码兼容 Java 8 (可按需设)
        targetCompatibility = rootProject.ext.targetCompatibility
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:${androidxAppcompatVersion}"
    implementation "com.google.android.material:material:${comGoogleAndroidMaterialVersion}"
    implementation "androidx.constraintlayout:constraintlayout:${androidxConstraintlayoutVersion}"

    implementation project(':libutils')
    // For debug online
    implementation project(':libausbc')

    /*BaiDu - ocrsdk*/
    implementation(name: 'ocrsdk', ext: 'aar')

    /*opencv*/
    /*implementation 'org.opencv:opencv:4.9.0'*/
    /*opencv-contrib*/
    implementation 'com.quickbirdstudios:opencv-contrib:4.5.3.0'

    /*ZXing*/
    implementation 'com.google.zxing:core:3.3.3'

    // ML Kit 扫码
    implementation 'com.google.mlkit:barcode-scanning:17.2.0'
    // 独立离线包 (模型直接内置在 App 内)
    // 识别拉丁字符、英文、数字等
    /*implementation 'com.google.mlkit:text-recognition:16.0.1'*/
    // 中文扩展包
    /*implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'*/
}