apply plugin: 'com.android.library'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        // 源代码兼容 Java 8 (可按需设)
        sourceCompatibility = rootProject.ext.sourceCompatibility
        // 生成的字节码兼容 Java 8 (可按需设)
        targetCompatibility = rootProject.ext.targetCompatibility
    }

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }

    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
        // The demo app does not have translations.
        disable 'MissingTranslation'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    // 使用原生 externalNativeBuild 替代手写 ndkBuild / ndkClean 任务
    externalNativeBuild {
        ndkBuild {
            // 替为实际 Android.mk 或 Application.mk 路径
            path file('src/main/jni/Android.mk')
        }
    }

    // 解决 MergeJavaResWorkAction 重复打包 so 文件冲突
    packagingOptions {
        pickFirst 'lib/*/*.so'
    }
}

dependencies {
    implementation fileTree(dir: new File(buildDir, 'libs'), include: '*.jar')
    implementation "androidx.appcompat:appcompat:${androidxAppcompatVersion}"
    /*xlog*/
    implementation 'com.elvishew:xlog:1.11.0'
    /*libuvccommon*/
    implementation project(path: ':libuvccommon')
}